Repository wanted-team2/1week_calculation, pull requests merged in 2022-01, with the labels that each got.

#4 Feat: API 함수 수정 및 HomePage 컴포넌트 적용
  .gitignore
  src/App.jsx
  src/api/api.jsx
  src/api/index.jsx
  src/pages/HomePage/index.jsx
  src/pages/index.jsx
Labels: Feat

#9 :construction: WIP: 1번 환율 계산기 임시 틀 구현
  public/currencyInfo.json
  src/api/api.jsx
  src/api/getCurrencyApi.js
  src/api/index.jsx
  src/components/domain/FirstCalculator/index.jsx
  src/components/domain/index.jsx
  src/hooks/index.jsx
  src/hooks/useAsync/index.jsx
  src/pages/HomePage/index.jsx
  src/utils/constants/apiKey.js
  src/utils/constants/reducerKey.js
Labels: UI, 1번 계산기

#11 Feat: Mockdata 적용 및 onChange 함수 구현중 in 1번계산기
  src/api/getMockData.js
  src/api/index.jsx
  src/pages/HomePage/index.jsx
Labels: 1번 계산기

#14 Feat: checkValidate, addComma 함수 구현
  src/components/domain/FirstCalculator/index.jsx
  src/components/domain/FirstCalculatorForm/index.jsx
  src/utils/functions/index.js
Labels: Feat, 1번 계산기

#17 Refactor: 1번 계산기 컴포넌트분리 to FirstCalculatorForm
  src/components/domain/FirstCalculator/index.jsx
  src/components/domain/FirstCalculatorForm/index.jsx
  src/components/domain/index.jsx
Labels: 1번 계산기, Refactor

#15 Feat: 2번 계산기 구현 완료
  public/currencyInfo.json
  public/dummy.json
  src/components/base/AmountContainer/index.jsx
  src/components/base/SecondCalculator/index.jsx
  src/components/base/UserForm/index.jsx
  src/components/base/index.jsx
  src/pages/HomePage/index.jsx
  src/utils/constants/calculationKey.js
  src/utils/functions/index.js
Labels: 2번 계산기

#21 Config:Jest 환경설정
  .gitignore
  babel.config.js
  jest.config.js
  package.json
  src/components/domain/FirstCalculator/FirstCalculator.test.jsx
  yarn.lock
Labels: Config

#24 Refactor, Feat: FirstCalculator 컴포넌트 생성, 송금액 앞자리 0 제거 및 전체적인 주석처리
  src/components/base/FirstCalculatorInfo/index.jsx
  src/components/base/index.js
  src/components/domain/FirstCalculator/index.jsx
  src/components/domain/FirstCalculatorForm/index.jsx
  src/pages/HomePage/index.jsx
Labels: Feat, 1번 계산기, Refactor

#25 Fix: submit 방지 처리
  src/components/base/UserForm/index.jsx
  src/components/domain/FirstCalculatorForm/index.jsx
Labels: Fix, 2번 계산기

#26 Test: 1번 계산기 test 코드 작성
  babel.config.js
  jest.config.js
  package.json
  src/components/domain/FirstCalculator/FirstCalculator.test.jsx
  src/components/domain/FirstCalculatorForm/FirstCalculatorForm.test.jsx
  yarn.lock
Labels: 1번 계산기, Test
